spring:
 security:
   user:     name: admin
     password: admin

management:
  endpoints:
    web:
      base-path: /x2bee
      exposure:
        include:
          - "info"
          - "health"
          - "httptrace"
          - "metrics"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
